### ISSUE TITLE
Error migrating from roam to denote

### ISSUE THREAD

**Issue by j-minster** [bitspook/notes-migrator#3]
Hello, thank you for this package. I would like to get some help with this error I'm running into when trying to migrate from roam to denote: 

`migrate-org-roam-to-denote: Symbol’s function definition is void: org-roam-node-list`

I'm running doom, with emacs 28.2. I do have roam installed and can use it's other functions. 

Please let me know if I should provide more info. 

Thanks.

**Comment by bitspook** [comment]
Hey,

I just pushed an update which don't use this function in particular. May be if you try with new code it'll work.

Also, during testing on emacs 28 I didn't face an error. Can you also please run `M-x org-roam-version` and tell me what it says? In my case, it is `v2.2.1-3-g3615259`.

**Comment by j-minster** [comment]
Such a quick reply, thank you so much! I updated and now I'm running into: 

`migrate-org-roam-to-denote: Symbol’s function definition is void: org-roam-list-files`

I think I see the issue... I'm on roam `v1.2.3`. Maybe I should update to v2? But will this mess with my notes written in v1?

**Comment by bitspook** [comment]
> Maybe I should update to v2? But will this mess with my notes written in v1?

Yes and most likely not. org-roam v2 provides `org-roam-migration-wizard` (you can call it with `M-x`), which worked without a problem for me when I migrated my notes from org-roam v1 to v2. It also creates a backup of your org-roam notes before doing its stuff; so your notes should be safe. 

---

I should add a note in readme that org-roam v2 is required; I just assumed nobody would be using v1 anymore since it has been a while since v2 was released.

**Comment by j-minster** [comment]
I upgraded to roam v2 and everything went smoothly. Thank you again for this great tool, and thank you for helping me.
